[package]
name = "tokenizer"
version = "0.3.0"
authors = ["merl <merl.001.mia@gmail.com>"]

[features]
default = ["strings"]

strings = []

[dependencies]
unicode-segmentation = "1.2"
unicode_categories = "0.1"
lazy_static = "1.1"
regex = "1"
